<a href="https://colab.research.google.com/github/santokalayil/my_python_programs/blob/master/Numpy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

NumPy is meant for creating homogeneous n-dimensional arrays (n = 1..n). Unlike Python lists, all elements of a NumPy array should be of same type. so the following code is not valid if data type is provided

In [0]:
numpy_arr = np.array([1,2,"Hello",3,"World"], dtype=np.int32)  # Error

However, for python lists, this is a valid code

In [0]:
py_arr = [1,2,"Hello",3,"World"]  # Valid Code

## Advantages of Numpy

### 1. NumPy uses much less memory to store data
The NumPy arrays takes significantly less amount of memory as compared to python lists. It also provides a mechanism of specifying the data types of the contents, which allows further optimisation of the code.
As an example, we can create a simple array of six elements using a python list as well as by using numpy.array(...) , The difference in amount of memory occupied by it is quite astounding. See the example below

In [0]:
import numpy as np

py_arr = [1,2,3,4,5,6]
numpy_arr = np.array([1,2,3,4,5,6])

sizeof_py_arr = sys.getsizeof(1) * len(py_arr)           # Size = 168
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size   # Size = 48

### 2. Using NumPy for creating n-dimension arrays
An n-dimension array is generally used for creating a matrix or tensors, again mainly for the mathematical calculation purpose. Compare to python list base n-dimension arrays, NumPy not only saves the memory usage, it provide a significant number of additional benefits which makes it easy to mathematical calculations
Here is a list of things we can do with NumPy n-dimensional arrays which is otherwise difficult to do.
The dimensions of the array can be changed at runtime as long as the multiplicity factor produces the same number of elements. For example, a 2 * 5 matrix can be converted into 5 * 2 and a 1 * 4 into 2 * 2. This can be done by calling the NumPy .reshape(...) function on the arrays

In [0]:
import numpy as np
# A 2 * 5 matrix
np_md_arr = np.array ( [ 
                        [1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10]
                        ] )

# Creates a 5 * 2 Matrix
# [ [1,2], [3,4], [5,6], [7,8], [9,10]]
np_modmd_arr = np_md_arr.reshape(5,2) 

# A 1 * 4 Matrix
np_md_arr2 = np.array ( [1, 2, 3, 4] )

# Creates a 2 * 2 Matrix
#[ [1,2], [3,4] ]
np_modmd_arr2 = np_md_arr2.reshape(2,2)

### 3. Mathematical operations on NumPy n-Dimension Arrays
As stated earlier, NumPy is not only about efficient storing the data, it also makes it extremely easy to perform mathematical operations on it. Any actions on n-dimension arrays behaves exactly similar to mathematical operations.
NumPy n-dimensional arrays makes it extremely easy to perform mathematical operations on it
This is the main USP of NumPy because of which it’s widely used in data analytic community. The python lists are nowhere near to what it can do. Let for example, consider multiplying a python list by 2. Here is what we’ll get

In [0]:
py_arr = [1,2,3] * 2
# Generates [1,2,3,1,2,3]

Whereas a numpy array produces the output, which each array elements are multiplied by 2

In [0]:
np_arr = np.array([1,2,3]) * 2
# Generates [2,4,6]

Similarly, we can also do other mathematical operations on numpy arrays like addition, subtractions and divisions

In [0]:
np_arr = np.array([1,2,3]) + 2
# Generates [3,4,5]

A Multi dimensional matrix operations are as easy as we do using two numbers

In [0]:
np_arr1 = np.array([[1,2,3],[4,5,6]])
np_arr2 = np.array([[1,2,3],[4,5,6]])
np_arr3 = np_arr1 * np_arr2
#Generates
# [[ 1  4  9]
# [16 25 36]]
np_arr3 = np_arr1 + np_arr2
#Generates
# [[ 2  4  6]
# [ 8 10 12]]

NumPy built-in mathematical functions also allow us to perform complex mathematical operations like sqrt, mean and median.

In [0]:
np.sqrt(np_arr1)
#generates
# [1.         1.41421356 1.73205081]
# [2.         2.23606798 2.44948974]]
np.mean(np_arr1) #generates 3.5
np.median(np_arr1) #generates 3.5

There are additional in-built members functions to get more details of the arrays, including sum, min and max

In [0]:
np_arr1.sum()  # 21
np_arr1.min()  # 1
np_arr1.max()  # 6

### 4. Finding Elements in NumPy array
While working with data sets there will be times when we need to find specific data from the available data set. Though NumPy provides multiple functions for the same, three of them will be used more often than others. They are where, nonzeroand count_nonzero.  
Where and nonzero functions returns the index associated with the True statement. for example

In [0]:
np_arr = np.array([1,2,0,4,5])
find = np.where(np_arr > 2)
#returns [3,4]

and

In [0]:
np_arr = np.array([1,2,0,4,5])
find = np.nonzero(np_arr)
# return [0,1,3,4]

And finally one can count the number of non zero elements in a numpy array by using count_nonzero(...) function

In [0]:
n_arr = np.array([1,2,3,0,3,0,2,0,0,2])
np.count_nonzero(n_arr) 
# returns 6

These methods are very useful in cases like calculating the sparsity or the density of a matrix.
The final method which has its own usage in machine learning is to find the shape of the NumPy array. This is done using .shape . For example

In [0]:
n_arr = np.array([1,2,3,0,3,0,2,0,0,2])
n_arr.shape
# Generates => (10,)
n_arr = np.array([[1,2],[3,0]])
# Generates => (2,2)

*Copyright &copy; Avinash.  All rights reserved.*